spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:172.16.101.39}:${DB_PORT:5432}/${DB_NAME:nspace}?stringtype=unspecified
    username: ${DB_USERNAME:xdp}
    password: ${DB_PASSWORD:gjEyCJRruMz28kw96OWXy5JBN9pOROXT}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # Chế độ tạo bảng: create / update / none
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: e_auth_service
    jackson:
      time-zone: Asia/Ho_Chi_Minh